export type PlatformStatus = "normal" | "syncing" | "error" | "unbound";

export interface InventoryItem {
  id: string;
  name: string;
  sku: string;
  category: string;
  currentStock: number;
  safetyStock: number;
  price: number;
  unit: string;
  meituanStatus: PlatformStatus;
  meituanStock: number;
  elemeStatus: PlatformStatus;
  elemeStock: number;
  jddjStatus: PlatformStatus;
  jddjStock: number;
}

export const platformLabel: Record<PlatformStatus, string> = {
  normal: "正常",
  syncing: "同步中",
  error: "异常",
  unbound: "未绑定",
};

export const platformColor: Record<PlatformStatus, string> = {
  normal: "bg-green-100 text-green-700",
  syncing: "bg-orange-100 text-orange-700",
  error: "bg-red-100 text-red-700",
  unbound: "bg-gray-100 text-gray-500",
};

export const mockInventory: InventoryItem[] = [
  {
    id: "1",
    name: "可口可乐 330ml 罐装",
    sku: "COKE-330",
    category: "饮料",
    currentStock: 45,
    safetyStock: 10,
    price: 3.5,
    unit: "罐",
    meituanStatus: "normal",
    meituanStock: 45,
    elemeStatus: "normal",
    elemeStock: 45,
    jddjStatus: "unbound",
    jddjStock: 0,
  },
  {
    id: "2",
    name: "农夫山泉 550ml",
    sku: "NFS-550",
    category: "饮料",
    currentStock: 120,
    safetyStock: 20,
    price: 2.0,
    unit: "瓶",
    meituanStatus: "normal",
    meituanStock: 120,
    elemeStatus: "syncing",
    elemeStock: 118,
    jddjStatus: "normal",
    jddjStock: 120,
  },
  {
    id: "3",
    name: "康师傅红烧牛肉面 110g",
    sku: "KSF-NOODLE-110",
    category: "方便食品",
    currentStock: 8,
    safetyStock: 15,
    price: 4.5,
    unit: "袋",
    meituanStatus: "normal",
    meituanStock: 8,
    elemeStatus: "normal",
    elemeStock: 8,
    jddjStatus: "normal",
    jddjStock: 8,
  },
  {
    id: "4",
    name: "德芙丝滑牛奶巧克力 80g",
    sku: "DOVE-80",
    category: "零食",
    currentStock: 32,
    safetyStock: 5,
    price: 15.9,
    unit: "盒",
    meituanStatus: "error",
    meituanStock: 30,
    elemeStatus: "normal",
    elemeStock: 32,
    jddjStatus: "normal",
    jddjStock: 32,
  },
  {
    id: "5",
    name: "维达抽纸 3层 120抽×3包",
    sku: "VIDA-TISSUE-3P",
    category: "日用品",
    currentStock: 15,
    safetyStock: 10,
    price: 12.9,
    unit: "提",
    meituanStatus: "normal",
    meituanStock: 15,
    elemeStatus: "normal",
    elemeStock: 15,
    jddjStatus: "syncing",
    jddjStock: 13,
  },
  {
    id: "6",
    name: "三只松鼠坚果大礼包 750g",
    sku: "SZS-750",
    category: "零食",
    currentStock: 3,
    safetyStock: 10,
    price: 89.0,
    unit: "盒",
    meituanStatus: "normal",
    meituanStock: 3,
    elemeStatus: "unbound",
    elemeStock: 0,
    jddjStatus: "unbound",
    jddjStock: 0,
  },
  {
    id: "7",
    name: "海飞丝去屑洗发水 400ml",
    sku: "HFS-400",
    category: "日用品",
    currentStock: 25,
    safetyStock: 8,
    price: 49.9,
    unit: "瓶",
    meituanStatus: "normal",
    meituanStock: 25,
    elemeStatus: "normal",
    elemeStock: 25,
    jddjStatus: "normal",
    jddjStock: 25,
  },
  {
    id: "8",
    name: "百威啤酒 330ml×6罐",
    sku: "BUD-330-6",
    category: "酒类",
    currentStock: 60,
    safetyStock: 12,
    price: 29.9,
    unit: "提",
    meituanStatus: "normal",
    meituanStock: 60,
    elemeStatus: "error",
    elemeStock: 58,
    jddjStatus: "normal",
    jddjStock: 60,
  },
  {
    id: "9",
    name: "乐事薯片 原味 75g",
    sku: "LAYS-ORIG-75",
    category: "零食",
    currentStock: 50,
    safetyStock: 15,
    price: 8.9,
    unit: "袋",
    meituanStatus: "normal",
    meituanStock: 50,
    elemeStatus: "normal",
    elemeStock: 50,
    jddjStatus: "normal",
    jddjStock: 50,
  },
  {
    id: "10",
    name: "蒙牛纯牛奶 250ml×12盒",
    sku: "MENGNIU-250-12",
    category: "乳制品",
    currentStock: 18,
    safetyStock: 15,
    price: 55.0,
    unit: "箱",
    meituanStatus: "syncing",
    meituanStock: 17,
    elemeStatus: "normal",
    elemeStock: 18,
    jddjStatus: "normal",
    jddjStock: 18,
  },
];
